clientes/urls.py
from django.urls import path
from clientes import views

urlpatterns = [
    path('', views.client_list, name='client_list'),
    path('cadastrar_cliente/', views.create_client, name='cadastrar_cliente'),
    path('client_update/<int:id>', views.client_update, name='client_update'),
    path('client_delete/<int:id>', views.client_delete, name='client_delete'),

    path('cadastrar_pet/<int:id>', views.create_pet, name='cadastrar_pet'),
    path('pet_list/<int:id>', views.pet_list, name='pet_list'),
    path('pet_update/<int:id>', views.pet_update, name='pet_update'),
    path('pet_delete/<int:id>', views.pet_delete, name='pet_delete'),
]

core/urls.py
from django.urls import path
from core import views

urlpatterns = [
    path('', views.home, name='home'),
]

petshop/urls.py
from django.contrib import admin
from django.urls import path, include
from core import urls as core_urls
from clientes import urls as clientes_urls
from funcionarios import urls as funcionarios_urls
from itens import urls as produtos_servicos_urls
from vendas import urls as vendas_urls
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(core_urls)),
    path('clientes/', include(clientes_urls), name='clientes'),
    path('funcionarios/', include(funcionarios_urls), name='funcionarios'),
    path('produtos_servicos/', include(produtos_servicos_urls), name='produtos_servicos'),
    path('vendas/', include(vendas_urls), name='vendas'),
]


handler404 = 'core.views.handle_page_not_found'

clientes/models.py
from django.db import models

class ClienteManager(models.Manager):

    def search(self, query):
        return self.get_queryset().filter(
            models.Q(name__icontains=query) |
            models.Q(cpf__icontains=query)
        )

class Cliente(models.Model):
    name = models.CharField('Nome completo', max_length=100, blank=False)
    cpf = models.CharField('CPF', max_length=15, blank=False, unique=True, null=False)
    telephone = models.CharField('Telefone', max_length=12, blank=False, null=True)
    rua = models.CharField('Rua', max_length=200, blank=True, null=True)
    cep = models.CharField('CEP', max_length=9, blank=True, null=True)
    bairro = models.CharField('Bairro', max_length=30, blank=True, null=True)
    cidade = models.CharField('Cidade', max_length=20, blank=True, null=True)
    numero = models.CharField('Número', max_length=5, blank=True, null=True)
    complemento = models.CharField('Complemento', max_length=20, blank=True, null=True)
    date_of_birth = models.DateField('Data de nascimento', blank=True, null=True)

    objects = ClienteManager()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'
        ordering = ['name']

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('client_update', args=[str(self.id)])




class PetManager(models.Manager):

    def search(self, query):
        return self.get_queryset().filter(
            models.Q(name__icontains=query) |
            models.Q(owner__icontains=query)
        )

class Pet(models.Model):

    owner = models.ForeignKey(Cliente, verbose_name='Cliente', on_delete=models.CASCADE)
    name = models.CharField('Nome', max_length=50, blank=True, null=True)
    date_of_birth = models.DateField('Data de Nascimento', blank=True, null=True)
    age = models.IntegerField('Idade', blank=True, null=True)
    created_at = models.DateTimeField('Cadastrado em', auto_now_add=True)
    species = models.CharField('Espécie', max_length=20, choices=(
        ('C', 'Cachorro'), ('G', 'Gato'), ('A', 'Ave'), ('R', 'Roedor'), ('P', 'Peixe'), ('R', 'Reptil'), ('Os', 'Outros')),
                               blank=False, null=True)
    breed = models.CharField('Raça', max_length=30, null=True, blank=True)
    gender = models.CharField('Gênero', max_length=8, choices=(('F', 'Fêmea'), ('M', 'Macho'), ('I', 'Indefinido')))

    objects = PetManager()

    def __str__(self):
        return self.name + '(' + self.owner.name + ')'


    class Meta:
        verbose_name = 'Animal'
        verbose_name_plural = 'Animais'
        ordering = ['owner', 'name']

clientes/forms.py
from django import forms
from .models import Pet, Cliente
from django.forms import Select, DateInput

SPECIES_CHOICES = (('', 'Espécie'), ('C', 'Cachorro'), ('G', 'Gato'), ('A', 'Ave'), ('R', 'Roedor'),
                   ('P', 'Peixe'), ('R', 'Reptil'), ('Os', 'Outros'))
GENDER_CHOICES = (('', 'Gênero'), ('F', 'Fêmea'), ('M', 'Macho'), ('I', 'Indefinido'))

class ClienteCreateForm(forms.ModelForm):
    cpf = forms.CharField(max_length=11, min_length=11)

    class Meta:
        model = Cliente
        fields = ['name', 'date_of_birth', 'cpf', 'telephone', 'rua', 'numero', 'bairro', 'cidade', 'complemento', 'cep']

        widgets = {
            'date_of_birth': forms.DateInput(attrs={'class': 'form-control'})
        }

class PetCreateForm(forms.ModelForm):
    class Meta:
        model = Pet
        fields = ['name', 'date_of_birth', 'age', 'species', 'breed', 'gender']

    def __init__(self, *args, **kwargs):
        super(PetCreateForm, self).__init__(*args, **kwargs)
        self.fields['species'].widget = Select(choices=SPECIES_CHOICES, attrs={'class': 'form-control'})
        self.fields['gender'].widget = Select(choices=GENDER_CHOICES, attrs={'class': 'form-control'})
        self.fields['date_of_birth'].widget = DateInput(attrs={'class': 'form-control'})

    def set_owner(self, id):
        pet = super(PetCreateForm, self).save(commit=False)
        pet.owner = id
        return pet.owner

clientes/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Cliente, Pet
from django.contrib import messages
from .forms import PetCreateForm, ClienteCreateForm
from django.contrib.auth.decorators import login_required

# ------------- CLIENTE -------------- #

@login_required(login_url='/')
def create_client(request):
    template_name = 'clientes/cadastrar_cliente.html'
    storaged = messages.get_messages(request)
    cliente = None

    if(request.method == 'GET'):
        form = ClienteCreateForm(request.GET or None)
    elif(request.method == 'POST'):
        form = ClienteCreateForm(request.POST)
        if form.is_valid():
            cliente = form.save()
            messages.success(request, 'Cliente incluído com sucesso.')
            return redirect('client_update', id=cliente.id)


    context = {
        'form': form,
        'message': storaged,
    }
    return render(request, template_name, context)


@login_required(login_url='/')
def client_list(request):
    clients = Cliente.objects.all()
    template_name = 'clientes/client_list.html'
    return render(request, template_name, {'clients': clients})


@login_required(login_url='/')
def client_update(request, id):
    client = get_object_or_404(Cliente, pk=id)
    storaged = messages.get_messages(request)
    form = ClienteCreateForm(request.POST or None, instance=client)
    template_name = 'clientes/client_update.html'
    context = {'client': client, 'form': form, 'message': storaged}

    if form.is_valid():
        form.save()
        context['success'] = True

    return render(request, template_name, context)


@login_required(login_url='/')
def client_delete(request, id):
    client = get_object_or_404(Cliente, pk=id)

    client.delete()
    messages.success(request, 'Cliente excluído com sucesso.')

    return redirect('client_list')



# --------------- PET ---------------- #


@login_required(login_url='/')
def create_pet(request, id):
    owner = get_object_or_404(Cliente, pk=id)
    template_name = 'clientes/cadastrar_pet.html'
    context = {}

    if request.method == 'POST':
        form = PetCreateForm(request.POST)
        form.set_owner(owner)
        if form.is_valid():
            form.save()
            context['success'] = True
            form = PetCreateForm()
    else:
        form = PetCreateForm()

    context['form'] = form
    context['owner'] = owner
    return render(request, template_name, context)


@login_required(login_url='/')
def pet_list(request, id):
    owner = get_object_or_404(Cliente, pk=id)
    pets = Pet.objects.filter(owner=owner)
    storaged = messages.get_messages(request)
    template_name = 'clientes/pet_list.html'
    return render(request, template_name, {'pets': pets, 'owner': owner, 'message': storaged})


@login_required(login_url='/')
def pet_update(request, id):
    pet = get_object_or_404(Pet, pk=id)
    owner = get_object_or_404(Cliente, pk=pet.owner.id)
    template_name = 'clientes/pet_update.html'
    form = PetCreateForm(request.POST or None, instance=pet)

    if form.is_valid():
        form.save()
        messages.success(request, 'Dados atualizados com sucesso.')
        return redirect('pet_list', id=owner.pk)

    context = {'form': form, 'pet': pet, 'owner': owner}

    return render(request, template_name, context)


@login_required(login_url='/')
def pet_delete(request, id):
    pet = get_object_or_404(Pet, pk=id)
    owner = get_object_or_404(Cliente, pk=pet.owner.id)

    pet.delete()
    messages.success(request, 'Animal excluído com sucesso.')

    return redirect('pet_list', id=owner.pk)

clientes/templates/clientes/cadastrar_cliente.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <!-- Menu - Cadastro de Funcionários -->
    <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand" href="#">
            <img src="{% static 'css/imagens/check-form.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            Cadastro de Clientes
        </a>
    </nav>

    <!-- Formulário de Cadastro -->
    
    <form class="espacamento" method="post">
        {% csrf_token %}

        <fieldset>
            <!-- Campo de Nome -->
            <label>Nome</label>
            <input type="text"
                   name="{{ form.name.name }}"
                   class="form-control"
                   id="exampleNome"
                   placeholder="Digite o nome completo"
                   required>

                <ul class="text-center" style="font-size:12px; color: #C53F3F">
                  {% for error in form.name.errors %}
                    {{error}}
                  {% endfor %}
                </ul>

            <!-- Campo de CPF e Data de Nascimento -->
            <div class="row">
                <div class="col-4 campos">
                    <label>CPF</label>
                    <input type="number"
                           name="{{ form.cpf.name }}"
                           class="form-control"
                           id="exampleCPF"
                           maxlength="11"
                           minlength="11"
                           placeholder="Ex.: 123.123.123-12"
                           required>
                </div>

                    <ul class="text-center" style="font-size:12px; color: #C53F3F">
                      {% for error in form.cpf.errors %}
                        {{error}}
                      {% endfor %}
                    </ul>

                <div class="col-4 campos">
                    <label>Telefone</label>
                    <input type="number"
                           name="{{ form.telephone.name }}"
                           class="form-control"
                           id="exampleTelefone"
                           maxlength="11"
                           minlength="11"
                           placeholder="Ex.: (83) 91234-5678"
                           required>
                </div>
                    <ul class="text-center" style="font-size:12px; color: #C53F3F">
                      {% for error in form.telephone.errors %}
                        {{error}}
                      {% endfor %}
                    </ul>

                <div class="col-4 campos">
                    <label>Data de Nascimento</label>
                    <input type="date"
                           name="{{ form.date_of_birth.name }}"
                           class="form-control"
                           id="exampleData">
                </div>
                 <ul class="text-center" style="font-size:12px; color: #C53F3F">
                      {% for error in form.date_of_birth.errors %}
                        {{error}}
                      {% endfor %}
                    </ul>
            </div>

            <!-- Campo de Endereço -->
            <div class="row">
                <div class="col-8 campos">
                    <label>Endereço</label>
                    <input type="text"
                           name="{{ form.rua.name }}"
                           class="form-control"
                           id="exampleEndereco"
                           placeholder="Digite o endereço">
                </div>
                <ul class="text-center" style="font-size:12px; color: #C53F3F">
                      {% for error in form.rua.errors %}
                        {{error}}
                      {% endfor %}
                    </ul>

                <div class="col-4 campos">
                    <label>CEP</label>
                    <input type="number"
                           name="{{ form.cep.name }}"
                           class="form-control"
                           maxlength="8"
                           minlength="8"
                           id="exampleCEP"
                           placeholder="Digite o CEP">
                </div>
                <ul class="text-center" style="font-size:12px; color: #C53F3F">
                      {% for error in form.cep.errors %}
                        {{error}}
                      {% endfor %}
                    </ul>
            </div>

            <div class="row">
                <div class="col-5 campos">
                    <label>Bairro</label>
                    <input type="text"
                           name="{{ form.bairro.name }}"
                           class="form-control"
                           id="exampleBairro"
                           placeholder="Digite o bairro">

                    <ul class="text-center" style="font-size:12px; color: #C53F3F">
                      {% for error in form.bairro.errors %}
                        {{error}}
                      {% endfor %}
                    </ul>
                </div>

                <div class="col-5 campos">
                    <label>Cidade</label>
                    <input type="text"
                           name="{{ form.cidade.name }}"
                           class="form-control"
                           id="exampleCidade"
                           placeholder="Digite a cidade">

                    <ul class="text-center" style="font-size:12px; color: #C53F3F">
                      {% for error in form.cidade.errors %}
                        {{error}}
                      {% endfor %}
                    </ul>
                </div>

                <div class="col-2 campos">
                    <label>Nº</label>
                    <input type="number"
                           name="{{ form.numero.name }}"
                           class="form-control"
                           id="exampleNumero"
                           placeholder="Número">

                    <ul class="text-center" style="font-size:12px; color: #C53F3F">
                      {% for error in form.numero.errors %}
                        {{error}}
                      {% endfor %}
                    </ul>
                </div>
            </div>

            <div>
                <label class="campos">Complemento</label>
                <input type="text"
                       name="{{ form.complemento.name }}"
                       class="form-control"
                       id="exampleComplemento"
                       placeholder="Ex.: casa, apt...">

                <ul class="text-center" style="font-size:12px; color: #C53F3F">
                  {% for error in form.complemento.errors %}
                    {{error}}
                  {% endfor %}
                </ul>
            </div>
        </fieldset>

        <!-- Botões -->
        <div class="botao_cadastro">
            <button type="submit" class="btn btn-outline-primary">Cadastrar</button>
            <a href="{% url 'home' %}" class="btn btn-outline-danger">Cancelar</a>
        </div>
    </form>

{% endblock %}

clientes/templates/clientes/cadastrar_pet.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <!-- Menu - Cadastro de Funcionários -->
    <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand" href="#">
            <img src="{% static 'css/imagens/dog-logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            Cadastro de Animais
        </a>
    </nav>

    <!-- Formulário de Cadastro -->
    
    <form class="espacamento" method="post">
        {% csrf_token %}

        {% if success %}
            <p style="color: green; align: center">Animal cadastrado com sucesso!</p>
        {% endif %}

        <fieldset>
            <!-- Campo de CPF e Data de Nascimento -->
            <div class="row">
                <div class="col-6">
                    <label>Nome do animal</label>
                    <input name="{{ form.name.name }}"
                           type="text"
                           class="form-control"
                           id="exampleNomeAnimal"
                           placeholder="Digite o nome" required>

                    <ul class="text-center" style="font-size:12px; color: #C53F3F">
                      {% for error in form.name.errors %}
                        {{error}}
                      {% endfor %}
                    </ul>
                </div>

                <div class="col-4">
                    <label>Data de Nascimento</label>
                    <input name="{{ form.date_of_birth.name }}"
                           type="date"
                           class="form-control"
                           id="data"
                           required>

                    <ul class="text-center" style="font-size:12px; color: #C53F3F">
                      {% for error in form.date_of_birth.errors %}
                        {{error}}
                      {% endfor %}
                    </ul>
                </div>

                <div class="col-2">
                    <label>Idade</label>
                    <input  name="{{ form.age.name }}"
                            type="num"
                            id="idade"
                            class="form-control"
                            placeholder="Idade"
                            readonly>

                    <ul class="text-center" style="font-size:12px; color: #C53F3F">
                      {% for error in form.age.errors %}
                        {{error}}
                      {% endfor %}
                    </ul>
                </div>
            </div>

            <!-- Campo de Raça e Espécie -->
            <div class="row">
                    <div class="col-4 campos">
                        <label>Espécie</label>
                        <div class="form-group">
                            {{ form.species }}

                            <ul class="text-center" style="font-size:12px; color: #C53F3F">
                              {% for error in form.species.errors %}
                                {{error}}
                              {% endfor %}
                            </ul>
                        </div>
                    </div>

                    <div class="col-4 campos">
                        <label>Raça</label>
                        <input name="{{ form.breed.name }}"
                               type="text"
                               class="form-control"
                               id="exampleRaca"
                               placeholder="Digite a raça do animal"
                               required>

                        <ul class="text-center" style="font-size:12px; color: #C53F3F">
                          {% for error in form.breed.errors %}
                            {{error}}
                          {% endfor %}
                        </ul>
                    </div>

                    <div class="col-4 campos">
                        <label>Gênero</label>
                        <div class="form-group">
                            {{ form.gender }}

                            <ul class="text-center" style="font-size:12px; color: #C53F3F">
                              {% for error in form.gender.errors %}
                                {{error}}
                              {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>

            <!-- Botões -->
            <div class="botao_cadastro">
                <button type="submit" class="btn btn-outline-primary">Cadastrar</button>
                <a href="{% url 'pet_list' owner.pk %}" class="btn btn-outline-danger">Voltar</a>
            </div>
        </fieldset>
    </form>

    <!-- Script para calcular a idade do Pet -->
    <script>
    document.getElementById("data").addEventListener('change', function() {
        var data = new Date(this.value);
        if(isDate_(this.value) && data.getFullYear() > 1800)
            document.getElementById("idade").value = calculateAge(this.value);
      });
    
      function calculateAge(dobString) {
        var dob = new Date(dobString);
        var currentDate = new Date();
        var currentYear = currentDate.getFullYear();
        var birthdayThisYear = new Date(currentYear, dob.getMonth(), dob.getDate());
        var age = currentYear - dob.getFullYear();
        if(birthdayThisYear > currentDate) {
          age--;
        }
        return age;
      }
    
      function calcular(data) {
        var data = document.form.nascimento.value;
        alert(data);
        var partes = data.split("/");
        var junta = partes[2]+"-"+partes[1]+"-"+partes[0];
        document.form.idade.value = (calculateAge(junta));
      }
    
      var isDate_ = function(input) {
              var status = false;
              if (!input || input.length <= 0) {
                status = false;
              } else {
                var result = new Date(input);
                if (result == 'Invalid Date') {
                  status = false;
                } else {
                  status = true;
                }
              }
              return status;
      }
    </script>

{% endblock %}

clientes/templates/clientes/client_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Apagar Cliente</title>
</head>
<body>

    <h1>Apagar Cliente</h1>

    <form method="post">
        {% csrf_token %}

        <p> <strong>Nome:</strong> {{ form.name.value }} </p>
        <p> <strong>Data de Nascimento:</strong> {{ form.date_of_birth.value }} </p>
        <p> <strong>CPF:</strong> {{ form.cpf.value }} </p>

        <h5 style="color: red">Atenção: alteração não pode ser desfeita!</h5>
        <button type="submit"> Apagar </button>
    </form>
        <a href="{% url 'client_list' %}">Voltar</a>


</body>
</html>

clientes/templates/clientes/client_list.html
{% extends 'base.html' %}
{% block content %}

<div class="container-fluid">

    <h1>Clientes</h1>
    <hr>
    {% if messages %}
        {% for message in messages %}
            <div>
                <center><p style="color: green; align: center"> {{ message }} </p></center>
            </div>
        {% endfor %}
    {% endif %}

    <div class="card mb-3">
      <div class="card-header">
        <i class="fas fa-table"></i>
        Lista de Clientes
            <div class="float-right float-sm-right float-md-right float-lg-right float-xl-right">
                <a href="{% url 'cadastrar_cliente' %}" class="btn btn-success btn-icon-split ">
                <span class="icon text-white-50">
                  <i class="fas fa-plus"></i>
                </span>
                <span class="text">Novo Cliente</span>
                </a>
            </div>
      </div>
        <div class="card-body">
        <div class="table-responsive">
        </thead>
          <table class="table table-hover" id="dataTable" width="100%" cellspacing="0">
            <thead>
              <tr>
                <th width="20%"><center>CPF</center></th>
                <th width="30%"><center>Nome</center></th>
                <th width="25%"><center>Data de Nascimento</center></th>
                <th width="25%"><center>Opções</center></th>
              </tr>
            </thead>
            <tbody>
                {% for client in clients %}
                  <tr>
                    <td width="20%"><strong><center>{{ client.cpf|default_if_none:'-' }}</center></strong></td>
                    <td width="30%"><center>{{ client.name|default_if_none:'-' }}</center></td>
                    <td width="25%"><center>{{ client.date_of_birth|default_if_none:'-' }}</center></td>
                    <td width="25%">
                    <center>
                        <a title="ver animal" href="{% url 'pet_list' client.pk %}" class="btn btn-circle btn-sm"><i class="fas fa-dog"></i></a>
                        <a title="editar" href="{% url 'client_update' client.pk %}" class="btn btn-circle btn-sm"><i class="fas fa-edit"></i></a>
                        <a title="excluir" class="btn btn-sm ml-2"><i class="fas fa-trash" data-toggle="modal" data-target="#excluirCliente{{client.id}}"></i></a>
                    </center>
                    </td>
                  </tr>

                  <!-- Modal -->
                  <div class="modal fade" id="excluirCliente{{client.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title" id="exampleModalCenterTitle">Excluir cliente</h5>
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                        <div class="modal-body">
                            Clique "Exluir" para excluir o cliente do sistema. Não é possível reverter esta ação!
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-info" data-dismiss="modal">Voltar</button>
                          <a href="{% url 'client_delete' client.pk %}" class="btn btn-danger">Excluir</a>
                        </div>
                      </div>
                    </div>
                  </div>
                {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
      <div class="card-footer small text-muted">Nunca compartilhe dados pessoais com terceiros e sempre trate tais informações pessoais de maneira estritamente confidencial.</div>

    </div>

<!-- /.container-fluid -->

</div>

{% endblock %}

clientes/templates/clientes/pet_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Apagar Animal</title>
</head>
<body>

    <h1>Apagar Cliente</h1>

    <form method="post">
        {% csrf_token %}

        <p> <strong>Nome do Animal:</strong> {{ pet.name }} </p>
        <p> <strong>Data de Nascimento:</strong> {{ pet.date_of_birth }} </p>

        <h5 style="color: red">Atenção: alteração não pode ser desfeita!</h5>
        <button type="submit"> Apagar </button>
    </form>
        <a href="{% url 'pet_list' owner.pk %}">Voltar</a>




</body>
</html>

clientes/templates/clientes/pet_list.html
{% extends 'base.html' %}
{% block content %}

<div class="container-fluid">

    <h1>
        Animais
    </h1>

    <hr>

    {% if messages %}
        {% for message in messages %}
            <div>
                <center><p style="color: green"> {{ message }} </p></center>
            </div>
        {% endfor %}
    {% endif %}

    <div class="card mb-3">
      <div class="card-header">
        <i class="fas fa-table"></i>
        {{ owner.name }}
          <div class="float-right float-sm-right float-md-right float-lg-right float-xl-right">
          <a href="{% url 'cadastrar_pet' owner.id %}" class="btn btn-success btn-icon-split ">
            <span class="icon text-white-50">
              <i class="fas fa-plus"></i>
            </span>

            <span class="text">Adicionar Pet</span>

          </a>
        </div>
      </div>
      <div class="card-body">
        <div class="table-responsive">
        </thead>
          <table class="table table-hover" id="dataTable" width="100%" cellspacing="0">
            <thead>
              <tr>
                <th>ID</th>
                <th>Nome</th>
                <th>Espécie</th>
                <th>Raça</th>
                <th>Gênero</th>
                <th>Data de Nascimento</th>
                <th>Idade</th>
                <th>Opções</th>
              </tr>
            </thead>
            <tbody>
            {% for pet in pets %}
              <tr>
                <td>{{ pet.id }}</td>
                <td>{{ pet.name|default_if_none:'-' }}</td>
                <td>{{ pet.get_species_display }}</td>
                <td>{{ pet.breed|default_if_none:'-' }}</td>
                <td>{{ pet.get_gender_display }}</td>
                <td>{{ pet.date_of_birth|default_if_none:'-' }}</td>
                <td>{{ pet.age }}</td>
                <td><a title="editar" href="{% url 'pet_update' pet.id %}" class="btn btn-circle btn-sm"><i class="fas fa-edit"></i></a>
                    <a title="excluir" class="btn btn-sm ml-2"><i class="fas fa-trash" data-toggle="modal" data-target="#excluirAnimal{{pet.id}}"></i></a>
                </td>
              </tr>

              <!-- Modal -->
              <div class="modal fade" id="excluirAnimal{{pet.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalCenterTitle">Excluir Animal</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                        Clique "Excluir" para excluir o animal. Não é possível reverter esta ação!
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-info" data-dismiss="modal">Voltar</button>
                      <a href="{% url 'pet_delete' pet.id %}" class="btn btn-danger">Excluir</a>
                    </div>
                  </div>
                </div>
              </div>
            {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
      <div class="card-footer small text-muted">Nunca compartilhe dados pessoais com terceiros e sempre trate tais informações pessoais de maneira estritamente confidencial.</div>

    </div>
</div>
    <!-- /.container-fluid -->

{% endblock %}