core/urls.py
from django.urls import path
from core import views

urlpatterns = [
    path('', views.home, name='home'),
]

petshop/urls.py
from django.contrib import admin
from django.urls import path, include
from core import urls as core_urls
from clientes import urls as clientes_urls
from funcionarios import urls as funcionarios_urls
from itens import urls as produtos_servicos_urls
from vendas import urls as vendas_urls
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(core_urls)),
    path('clientes/', include(clientes_urls), name='clientes'),
    path('funcionarios/', include(funcionarios_urls), name='funcionarios'),
    path('produtos_servicos/', include(produtos_servicos_urls), name='produtos_servicos'),
    path('vendas/', include(vendas_urls), name='vendas'),
]


handler404 = 'core.views.handle_page_not_found'

vendas/urls.py
from django.urls import path
from vendas import views

urlpatterns = [
    path('', views.vendas_list, name='vendas_list'),
    path('cadastrar_vendas/', views.vendas_create, name='cadastrar_vendas'),
    path('cupom_fiscal/<int:id>', views.get_pdf, name='cupom_fiscal'),
    path('relatorio_vendas/', views.relatorio_vendas, name='relatorio_vendas'),

]

vendas/models.py
from django.db import models
from funcionarios.models import User
from clientes.models import Cliente
from itens.models import Item


class ItemCompradoManager(models.Manager):

    def search(self, query):
        return self.get_queryset().filter(
            models.Q(item__icontains=query)
        )

class ItemComprado(models.Model):
    item = models.ForeignKey(Item, verbose_name='Item', on_delete=models.CASCADE)
    qnt = models.IntegerField(default=1, blank=True, null=True)
    subtotal = models.DecimalField(max_digits=7, decimal_places=2)

    objects = ItemCompradoManager()


class VendasManager(models.Manager):

    def search(self, query):
        return self.get_queryset().filter(
            models.Q(code__icontains=query) |
            models.Q(date__icontains=query) |
            models.Q(cliente__icontains=query)
        )

class Vendas(models.Model):

    date = models.DateTimeField('Data da venda')
    funcionario = models.ForeignKey(User, verbose_name='Funcionário', on_delete=models.CASCADE)
    cliente = models.ForeignKey(Cliente, verbose_name='Cliente', on_delete=models.CASCADE)
    itens = models.ManyToManyField(ItemComprado, blank=True)
    valor_total = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    forma_pagamento = models.CharField('Forma de Pagamento', max_length=20, choices=(
        ('D', 'Dinheiro'), ('CC', 'Cartão de Crédito'), ('CD', 'Cartão de Débito')), default=('D', 'Dinheiro'))

    objects = VendasManager()

    def __str__(self):
        return 'Código: %d - Cliente: %s ' % (self.pk, self.cliente)


    def calculaValor_total(self):
        valor_total = 0
        for itemComprado in self.itens.all():
            valor_total += itemComprado.subtotal
        self.valor_total = valor_total

    class Meta:
        verbose_name = 'Venda'
        verbose_name_plural = 'Vendas'

vendas/forms.py
from django import forms
from .models import Vendas
from django.forms import formset_factory
from itens.models import Item
from django.core.validators import MinValueValidator
from itens.forms import MONTHS
from django.utils.timezone import now



class VendasForm(forms.ModelForm):
    class Meta:
        model = Vendas
        fields = ['date', 'funcionario', 'cliente', 'forma_pagamento']

        widgets = {
            'cliente': forms.Select(attrs={'class': 'form-control'}),
            'date': forms.SelectDateWidget(months=MONTHS, empty_label='Cliente',
                attrs={'data-max': now, 'class': 'form-control', 'style': 'width: 33.333%; display: inline-block; margin-bottom: 6px;'}),
            'forma_pagamento': forms.Select(attrs={'class': 'form-control'}),
            'funcionario': forms.Select(attrs={'class': 'form-control'})
        }


    def clean_date(self):
        date = self.cleaned_data.get('date')
        if date > now():
            raise forms.ValidationError('Não é possível cadastrar venda com data maior do que a atual.')
        return date



class AddItemForm(forms.Form):

    item = forms.ModelChoiceField(queryset=Item.objects.all(), required=True, widget=forms.Select(attrs={'class': 'form-control'}))
    quantidade = forms.IntegerField(validators=[MinValueValidator(1)], required=True,
                                    widget=forms.NumberInput(attrs={'class': 'form-control', 'style': 'margin-left: 15px;'}))

    def clean_quantidade(self):
        qntd = self.cleaned_data['quantidade']
        idItem = self['item'].value()

        if idItem != '':
            item = Item.objects.get(pk=idItem)

            if item.category == 'P':
                if item.quantity < qntd:
                    raise forms.ValidationError('Quantidade de %s indiponível.' % item.name)
                else:
                    item.baixaEstoqueProduto(qntd)
                    item.save()
        else:
            raise forms.ValidationError('Informações incorretas. Verifique os campos.')

        return qntd


ItemFormSet = formset_factory(AddItemForm, extra=1)


class PeriodoRelatorioVendas(forms.Form):

    data_inicial = forms.DateField(widget=forms.SelectDateWidget(months=MONTHS,
        attrs={'class': 'form-control', 'style': 'width: 33.333%; display: inline-block;'}))
    data_final = forms.DateField(widget=forms.SelectDateWidget(months=MONTHS,
        attrs={'class': 'form-control', 'style': 'width: 33.333%; display: inline-block;'}))

    def clean(self):
        start_date = self.cleaned_data.get("data_inicial")
        end_date = self.cleaned_data.get("data_final")
        if end_date < start_date:
            msg = u"End date should be greater than start date."
            self._errors["A data inicial deve ser menor que a data final."] = self.error_class([msg])
            # raise forms.ValidationError('Informações incorretas. Verifique os campos.')

vendas/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Vendas, ItemComprado
from django.utils.timezone import now
from django.contrib.auth.decorators import login_required
from .forms import VendasForm, ItemFormSet, PeriodoRelatorioVendas
from django.contrib import messages
from core.render import Render
from decimal import Decimal
from django.db.models import Sum
from django.contrib.admin.views.decorators import staff_member_required


@login_required(login_url='/')
def vendas_list(request):
    template_name = 'vendas/vendas_list.html'
    context = {}
    storaged = messages.get_messages(request)

    vendas = Vendas.objects.all()

    context['vendas'] = vendas
    context['messages'] = storaged

    return render(request, template_name, context)


@login_required(login_url='/')
def get_pdf(request, id):
    venda = get_object_or_404(Vendas, pk=id)
    tributo = Decimal(float(venda.valor_total) * 0.2215).quantize(Decimal('.01'))

    params = {
        'venda': venda,
        'tributo': tributo
    }
    return Render.render('vendas/cupom_fiscal.html', params)


@login_required(login_url='/')
def vendas_create(request):
    template_name = 'vendas/cadastrar_vendas.html'
    context = {}

    if request.method == 'GET':
        vendaForm = VendasForm(request.GET or None,
               initial={'funcionario': request.user, 'date': now})
        formset = ItemFormSet(request.GET or None)

    elif request.method == 'POST':
        vendaForm = VendasForm(request.POST, initial={'funcionario': request.user, 'date': now})
        formset = ItemFormSet(request.POST)

        if vendaForm.is_valid() and formset.is_valid():
            venda = vendaForm.save()
            context['venda'] = venda

            for form in formset:
                itemComprado = ItemComprado.objects.create(
                    item=form.cleaned_data.get('item'),
                    qnt=form.cleaned_data.get('quantidade'),
                    subtotal=form.cleaned_data.get('quantidade')*form.cleaned_data.get('item').price_of_sale
                )
                itemComprado.save()

                if itemComprado:
                    venda.itens.add(itemComprado)
                venda.calculaValor_total()
                venda.save()

            if venda.itens.exists():
                context['success'] = True
            else:
                venda.delete()
                messages.error(request, 'Venda sem itens não cadastrada.')
                return redirect('vendas_list')


    context['vendaForm'] = vendaForm
    context['formset'] = formset

    return render(request, template_name, context)


# def get(context):
#     return Render.render('vendas/relatorio_vendas_pdf.html', context)


@staff_member_required(login_url='/')
def relatorio_vendas(request):
    template_name = 'vendas/relatorio_vendas.html'
    form = PeriodoRelatorioVendas(initial={'data_inicial': now, 'data_final': now})
    context = {}
    total_vendido = Decimal(0).quantize(Decimal('.01'))

    if request.method == 'POST':
        form = PeriodoRelatorioVendas(request.POST, initial={'data_inicial': now, 'data_final': now})
        if form.is_valid():
            data_inicial = form.cleaned_data['data_inicial']
            data_final = form.cleaned_data['data_final']

            vendas = Vendas.objects.filter(date__range=[data_inicial, data_final]).order_by('date')
            if vendas:
                total_vendido = Decimal(vendas.aggregate(total=Sum('valor_total'))['total']).quantize(Decimal('.01'))

            context = {
                'vendas': vendas,
                'data_inicial': data_inicial,
                'data_final': data_final,
                'total_vendido': total_vendido
            }

            return Render.render('vendas/relatorio_vendas_pdf.html', context)

    context['form'] = form

    return render(request, template_name, context)

vendas/templates/vendas/cadastrar_vendas.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

    <div id="content-wrapper">

    <div class="container-fluid">
    <h1>Cadastrar Venda</h1>
    <hr>

    <form class="col-5 espacamento" method="POST">
        {% csrf_token %}
        <div class="botao">
            <img class="displayed" src="{% static  'css/imagens/shopping-bag.png' %}" alt="" width="100" height="100">
        </div>
        <fieldset>
        {% if success %}
            <p style="color: green" align="center">Venda cadastrada com sucesso!</p>
        {% endif %}
        {% if venda %}
            <div align="center">
                <div>
                    <a href="{% url 'cupom_fiscal' venda.pk %}" class="btn btn-success btn-icon-split " target="_blank">
                    <span class="icon text-white-50">
                      <i class="fas fa-file-alt"></i>
                    </span>
                    <span class="text">Cupom Fiscal</span>
                    </a>
                </div>
            </div>
        {% endif %}
            <!-- Campo de Cliente/Data -->
            <div class="row">
              <div class="campos form-group2 col-6">
                <label>Cliente</label>
                <div class="form-group">
                    {{ vendaForm.cliente }}
                    <ul class="text-center" style="font-size:12px; color: #C53F3F">
                      {% for error in vendaForm.cliente.errors %}
                        {{error}}
                      {% endfor %}
                    </ul>
                </div>
              </div>

              <div class="campos form-group2 col-6">
                <label>Data da venda</label>
                    <div>{{ vendaForm.date }}</div>
                    <ul class="text-center" style="font-size:12px; color: #C53F3F">
                      {% for error in vendaForm.date.errors %}
                        {{error}}
                      {% endfor %}
                    </ul>
              </div>
            </div>


            <!-- Campo de Item/Quantidade/Preço -->
        {{ formset.management_form }}
        {% for form in formset %}
        {{ form.non_field_errors }}
        {% for field in form %}
            <!--<div class="pure-control-group">-->
                <!--{{ field.errors }}-->
            <!--</div>-->
        {% endfor %}


        <div class="row form-row spacer">
            <div class="campos form-group2 col-8">
                <label>Item</label>
                <div>{{ form.item }}</div>
                <ul class="text-center" style="font-size:12px; color: #C53F3F">
                  {% for error in form.item.errors %}
                    {{error}}
                  {% endfor %}
                </ul>
            </div>

            <div class="campos form-group2 col-2">
                <label style="margin-left: 9px">Quantidade</label>
                <div>{{ form.quantidade }}</div>
            </div>

            <div class="campos form-group2 col-2">
                <label style="color: white"> _ </label>
                <div align="right"><button class="btn btn-success add-form-row">+</button></div>
            </div>

        </div>
        <p style="font-size:12px; color: #C53F3F">
          {% for error in form.quantidade.errors %}
            {{error}}
          {% endfor %}
        </p>

        {% endfor %}

            <div class="row">
                <div class="campos form-group2 col-5">
                <label>Forma de Pagamento</label>
                    <div>{{ vendaForm.forma_pagamento }}</div>
                    <ul class="text-center" style="font-size:12px; color: #C53F3F">
                      {% for error in vendaForm.forma_pagamento.errors %}
                        {{error}}
                      {% endfor %}
                    </ul>
                </div>
            <div class="campos form-group2 col-7">
                <label>Funcionário</label>
                    <div>{{ vendaForm.funcionario }}</div>
                    <ul class="text-center" style="font-size:12px; color: #C53F3F">
                      {% for error in vendaForm.forma_pagamento.errors %}
                        {{error}}
                      {% endfor %}
                    </ul>
                </div>
            </div>
        </fieldset>

        <!-- Botões Cadastrar/Cancelar -->
        <div class="botao">
            {% if not venda %}
            <button type="submit" class="btn btn-outline-primary">Cadastrar Venda</button>
            {% else %}
            <a href="{% url 'cadastrar_vendas' %}" class="btn btn-success btn-icon-split">Nova Venda</a>
            {% endif %}
            <a href="{% url 'vendas_list' %}" class="btn btn-outline-secondary">Voltar</a>
        </div>

    </form>
    </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>-->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script type="text/javascript">
    function updateElementIndex(el, prefix, ndx) {
        var id_regex = new RegExp('(' + prefix + '-\\d+)');
        var replacement = prefix + '-' + ndx;
        if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex, replacement));
        if (el.id) el.id = el.id.replace(id_regex, replacement);
        if (el.name) el.name = el.name.replace(id_regex, replacement);
    }
    function cloneMore(selector, prefix) {
        var newElement = $(selector).clone(true);
        var total = $('#id_' + prefix + '-TOTAL_FORMS').val();
        newElement.find(':input:not([type=button]):not([type=submit]):not([type=reset])').each(function() {
            var name = $(this).attr('name')
            if(name) {
                name = name.replace('-' + (total-1) + '-', '-' + total + '-');
                var id = 'id_' + name;
                $(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
            }
        });
        newElement.find('label').each(function() {
            var forValue = $(this).attr('for');
            if (forValue) {
              forValue = forValue.replace('-' + (total-1) + '-', '-' + total + '-');
              $(this).attr({'for': forValue});
            }
        });
        total++;
        $('#id_' + prefix + '-TOTAL_FORMS').val(total);
        $(selector).after(newElement);
        var conditionRow = $('.form-row:not(:last)');
        conditionRow.find('.btn.add-form-row')
        .removeClass('btn-success').addClass('btn-danger')
        .removeClass('add-form-row').addClass('remove-form-row')
        .html('-');
        return false;
    }
    function deleteForm(prefix, btn) {
        var total = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
        if (total > 1){
            btn.closest('.form-row').remove();
            var forms = $('.form-row');
            $('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);
            for (var i=0, formCount=forms.length; i<formCount; i++) {
                $(forms.get(i)).find(':input').each(function() {
                    updateElementIndex(this, prefix, i);
                });
            }
        }
        return false;
    }

    $(document).on('click', '.add-form-row', function(e){
        e.preventDefault();
        cloneMore('.form-row:last', 'form');
        return false;
    });
    $(document).on('click', '.remove-form-row', function(e){
        e.preventDefault();
        deleteForm('form', $(this));
        return false;
    });


    </script>

{% endblock %}

vendas/templates/vendas/cupom_fiscal.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Cupom Fiscal</title>
    <style type="text/css">
        @page {
            size: A4;
            margin: 1cm;
        }
        .table {
            width: 100%;
            max-width: 100%;
            margin-bottom: 5px;
            background-color: #fff;
        }
        .table th,
        .table td {
            padding: 5px;
            vertical-align: top;
            text-align: center;
        }
        .table th {
            border-top: none;
            border-bottom: 1px solid #000;
        }
        .table thead th {
            vertical-align: bottom;
            border-bottom: 2px solid #000;
        }
        .table tbody + tbody {
            border-top: 2px solid #000;
        }
        .table .table {
            background-color: #fff;
        }
        .list-group {
            display: block;
            width: 100%;
            list-style: none;
            margin-top: 15px;
            margin-bottom: 15px;
        }
        .list-group p {
            width: 100%;
            height: 20px;
            line-height: 20px;
            list-style: none;
            font-size: 1.1em;
        }
    </style>
</head>
    <body>

        <div class="container">
            <div class="card">
                <div class="card-header">
                    <center>
                        <img class="displayed" src="core/static/css/imagens/pet.png" alt="" width="100" height="100">
                        <H1>PETSHOP ALIBABÁ</H1>
                        <h3>Rodovia BR-230,km 22, s/n - Água Fria<br />
                        João Pessoa/PB CEP: 58.053-000</h3>
                        <h3>CNPJ: 11.222.333./0001-44<br />
                        IE: 000.000.000.000<br />
                        IM: 0.000.000-0</h3>
                    <hr></center>
                </div>

                <table class="table">
                    <thead>
                    <tr>
                        <th>{{ venda.date | date:"d/m/Y" }}</th>
                        <th>{{ venda.date | date:"H:i:s" }}</th>
                        <th>CCF: 000000</th>
                        <th>COO: 112233</th>
                    </tr>
                    </thead>
                </table>

                    <h2 style="font-size: 18px"><center>CUPOM FISCAL</center></h2>

                <ol>
                <table class="table">
                    <thead>
                    <tr>
                        <th>ITEM</th>
                        <th>CÓDIGO UN.</th>
                        <th>DESCRIÇÃO</th>
                        <th>QTD. UN.</th>
                        <th>VL. UNIT(R$)</th>
                        <th>VL. ITEM(R$)</th>
                    </tr>
                    </thead>
                    <tbody>

                    {% for itemComprado in venda.itens.all %}
                       <tr>
                            <td>{{ forloop.counter }} </td>
                            <td>{{ itemComprado.item.code }}</td>
                            <td>{{ itemComprado.item.name }} </td>
                            <td>{{ itemComprado.qnt }}UN  X   </td>
                            <td>R$ {{ itemComprado.item.price_of_sale }}</td>
                            <td>R$ {{ itemComprado.subtotal }}</td>
                        </tr>

                    {% endfor %}

                    <tr>
                        <th>TOTAL</th>
                        <th> </th>
                        <th> </th>
                        <th> </th>
                        <th> </th>
                        <th style="font-size: 15px">R$ {{ venda.valor_total }}</th>
                    </tr>
                    <tr>
                        <td>{{ venda.get_forma_pagamento_display }}</td>
                        <td> </td>
                        <td> </td>
                        <td> </td>
                        <td> </td>
                        <td style="font-size: 12px">R$ {{ venda.valor_total }}</td>
                    </tr>
                    </tbody>
                </table><p>Val. Aprox. Tributos R$ {{ tributo }} (22.15%)</p>
                </ol>
                <p>Vendedor: {{ venda.funcionario.id }} - {{ venda.funcionario.name }}</p>
            </div>
        </div>

    </body>
</html>

vendas/templates/vendas/relatorio_vendas.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

    <div id="content-wrapper">

        <div class="container-fluid">
        <h1>Relatório de Vendas</h1>
        <hr>

        <form class="col-5 espacamento" method="POST">
            {% csrf_token %}
            <div class="botao">
                <img class="displayed" src="{% static 'css/imagens/questionnaire.png' %}" alt="" width="70" height="70">
            </div>
            <fieldset>
                <center><p style="font-size:12px; color: #C53F3F">
                  {% for error in form.errors %}
                    {{error}}
                  {% endfor %}
                </p></center>


                <!-- Campo de Data Inicial/Data Final -->
                <div class="row">
                    <div class="campos form-group2 col-6">
                        <label>Data Incial</label>
                        <div>{{ form.data_inicial }}</div>
                        <ul class="text-center" style="font-size:12px; color: #C53F3F">
                        {% for error in form.name.errors %}
                        {{error}}
                        {% endfor %}
                        </ul>
                    </div>

                    <div class="campos form-group2 col-6">
                        <label>Data Final</label>
                        <div>{{ form.data_final }}</div>
                        <ul class="text-center" style="font-size:12px; color: #C53F3F">
                        {% for error in form.name.errors %}
                        {{error}}
                        {% endfor %}
                        </ul>
                    </div>
                </div>

            </fieldset>

            <!-- Botões -->
            <div class="botao">
                <button type="submit" class="btn btn-success btn-icon-split">Emitir Relatório</button>
            </div>
        </form>
        </div>
    </div>

{% endblock %}

vendas/templates/vendas/relatorio_vendas_pdf.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Relatório de Vendas</title>
    <style type="text/css">
        @page {
            size: A4;
            margin: 1cm;
        }
        .table {
            width: 100%;
            max-width: 100%;
            margin-bottom: 5px;
            background-color: #fff;
        }
        .table th,
        .table td {
            padding: 5px;
            vertical-align: top;
            text-align: center;
        }
        .table th {
            border-top: none;
            border-bottom: 1px solid #000;
        }
        .table thead th {
            vertical-align: bottom;
            border-bottom: 2px solid #000;
        }
        .table tbody + tbody {
            border-top: 2px solid #000;
        }
        .table .table {
            background-color: #fff;
        }
        .list-group {
            display: block;
            width: 100%;
            list-style: none;
            margin-top: 15px;
            margin-bottom: 15px;
        }
        .list-group p {
            width: 100%;
            height: 20px;
            line-height: 20px;
            list-style: none;
            font-size: 1.1em;
        }
    </style>
</head>
    <body>

        <div class="container">
            <div class="card">
                <div class="card-header">
                    <center>
                        <img class="displayed" src="core/static/css/imagens/pet.png" alt="" width="100" height="100">
                        <H1>PETSHOP ALIBABÁ</H1>
                    <hr></center>
                </div>
                <div><strong>Período: </strong>{{ data_inicial | date:"d/m/Y" }} a {{ data_final | date:"d/m/Y" }}</div>
                <table class="table">
                    <thead>
                    <tr>
                        <th width="100">Código</th>
                        <th width="150">Data</th>
                        <th width="200">Cliente</th>
                        <th width="100">Funcionário</th>
                        <th width="150">Valor da Venda</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for venda in vendas %}
                        <tr>
                        <td width="100">{{ venda.id }}</td>
                        <td width="150">{{ venda.date | date:"d/m/Y" }}</td>
                        <td width="200">{{ venda.cliente }}</td>
                        <td width="150">{{ venda.funcionario }}</td>
                        <td width="100">{{ venda.valor_total }}</td>
                        </tr>
                    {% endfor %}
                    <tr>
                        <th width="200" style="font-size: 12px">TOTAL VENDIDO</th>
                        <th width="150"> </th>
                        <th width="200"> </th>
                        <th width="100"> </th>
                        <th width="150" style="font-size: 12px">R$ {{ total_vendido }}</th>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>

    </body>
</html>

vendas/templates/vendas/vendas_list.html
{% extends 'base.html' %}
{% block content %}

    <div id="content-wrapper">

        <div class="container-fluid">

        <h1>Vendas</h1>
        <hr>
        <div class="card mb-3">
          <div class="card-header">
            <i class="fas fa-table"></i>
            Lista de Vendas


            <div class="float-right float-sm-right float-md-right float-lg-right float-xl-right">
                <a href="{% url 'cadastrar_vendas' %}" class="btn btn-success btn-icon-split ">
                <span class="icon text-white-50">
                  <i class="fas fa-shopping-cart"></i>
                </span>
                <span class="text">Nova Venda</span>
                </a>
            </div>

          </div>
          <div class="card-body">
            <div class="table-responsive">
            </thead>
              <table class="table table-hover" id="dataTable" width="100%" cellspacing="0">
                <thead>
                  <tr>
                    <th><center>Código</center></th>
                    <th><center>Cliente</center></th>
                    <th><center>Funcionário</center></th>
                    <th><center>Data da Venda</center></th>
                    <th><center>Valor Total</center></th>
                    <th><center>Opções</center></th>
                  </tr>
                </thead>
                <tbody>
                {% if messages %}
                {% for message in messages %}
                <div>
                    <p style="color: gray"><strong> {{ message }} </strong></p>
                </div>
                {% endfor %}
                {% endif %}

                {% for venda in vendas %}
                <tr>
                    <th><center>{{ venda.id }}</center></th>
                    <td><center>{{ venda.cliente }}</center></td>
                    <td><center>{{ venda.funcionario }}</center></td>
                    <td><center>{{ venda.date | date:"d/m/Y" }}</center></td>
                    <td><center>{{ venda.valor_total }}</center></td>
                <td>
                    <center><a href="{% url 'cupom_fiscal' venda.pk %}" class="btn btn-circle btn-sm" target="_blank"><i class="fas fa-file-alt"></i></a></center>
                </td>
                </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
          <div class="card-footer small text-muted">Nunca compartilhe dados pessoais com terceiros e sempre trate tais informações pessoais de maneira estritamente confidencial.</div>

        </div>
        </div>
    </div>
                <!-- /.container-fluid -->
{% endblock %}